# specify the version of docker-compose
version: "3.8"

# define the services/containers to be run
services:
  api: 
    # api service depends on the db service so the db service will be started before the api service
    depends_on: 
      - db
    build: ./backend
    ports: 
      - 8000:8000
    environment: 
      DB_URL: mongodb://db/anime
    # establish docker compose watch mode for the api service
    develop:
      # specify the files to watch for changes
      watch:
        # it'll watch for changes in package.json and package-lock.json and rebuild the container and image if there are any changes
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild
        
        # it'll watch for changes in the backend directory and sync the changes with the container real time
        - path: ./backend
          target: /app
          action: sync

  # define the db service
  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - anime:/data/db
volumes:
  anime: